services:
    redeye_sidekiq.predis:
        class: Predis\Client
        public: false
        arguments:
            - ~ # dsn

    redeye_sidekiq:
        class: SidekiqJobPusher\Client
        arguments:
            - @redeye_sidekiq.predis
            - ~

