services:
    redeye_sidekiq.predis:
        class: Predis\Client
        public: true
        arguments:
            - ~ # dsn

    redeye_sidekiq:
        class: SidekiqJobPusher\Client
        arguments:
            - "@redeye_sidekiq.predis"
            - ~

